spring:
    application:
        name: position-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: microservice
    cloud:
        config:
            override-system-properties: false
            allow-override: true
            override-none: true
server:
    port: 8082
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}