server:
    port: 8762
spring:
    application:
        name: zuul-server
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
zuul:
    prefix: /api
    ignored-services: '*'
    routes:
        employee-service:
            path: /employees/**
            strip-prefix: false
        position-service:
            path: /positions/**
            strip-prefix: false