spring:
    application:
        name: employee-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: microservice
server:
    port: 8081
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}